language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
script: py.test --cov=. --cov-report term-missing
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
deploy:
  provider: pypi
  user: Avalara
  password:
    secure: ZBRNf1sZdgiP9Z/hL187Dnd5mdphAuUznAxIrG05hSzN1ic0cU42UqrZ523Hy98Js9Z23HaRGjeVdy+P9iahsS9HlS8mpamRcWvofb3zVYn7PX+r0QAl1J9f0AzqNgfbXcaA9pp030YK+Zv2OPqnL2eiMtBZ59xxtUnDO/7BHJlAxe6t7hX13+IbjtfZ1F5ku0AcX/4tHeTXhuFi9+Lzn8AmL5PlBqwibVlz5JMwPzmwQMiYGvOSJSzVfaBkLWGuKZAOfY1Oon8ea7tvIYVfzfUoTz1Af0PRzjd/fZekHVR156mzSkPwa1QZ5zREQ6QEXVULiTob8sCtO3N3cMFLpGsz8L/qLx+VNfAYymJzcFC/UQLrZ80NN5+x/iacS9i4Ft32eViBZM4tGcQqAU8nzSgUPcOwwrCnAqsIqK9RrxzrvRuHce3lHPyh47oXVNKKlhmRGDW/lyOCbKfZ+7ftgA2mMHuj6ydf+kpxjwniwsG9gbfpa7mH4+lFLN2AaQ9xGZlc2W4VhtiTqyB1oeiVrh8eBFDp+PgSTXA3ECzSbWXHuYW7aFy0flNhKh6BAyYmnX66ObMGThMUS+Dmufx1IRXwzW9dGtzM6o9x6TuoRw0TqZXTjERZu2be8/lENlNy7DTmHpq/rMOWmuDiWlHeR68mOj6yGMxtRmcD8mOC8A4=
  on:
    tag: true
    branch: master
    python: 3.6
