language: python
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
jobs:
  include:
  - stage: Tests
    python:
    - '2.7'
    - '2.6'
    script: py.test --cov=. --cov-report term-missing
  - python: 3.6  
    stage: Deploy
    before_deploy:
    - python3 setup.py sdist
    deploy:
      provider: pypi
      user: Avalara
      password:
        secure: cCLjCZUuSjJOLj5L7SQE4pz9YMk6hyzEbJGY4p6f93wG4mzF2y2LGZhD3k6ZJtBCgxrEHRxAfQl2k5U7ZmDAu8iwsG//V1fLWHaiIHT26Ran29qkDat04xL3ILRcQyJUx7xIJ1cwbRlQR9X0vRjpfmUitQCPM0Zx6ZE7Wj+1NTNm5EUbmr0qj7ZiRP5LC4A8kOs2Wuhwh08QWIfI9qKOk/w6odos2JfT8alipKIVRzdON9XmcslgZL1/T6++iztw+JVAi//MJIaq3Tq9BR/uQ03Oa+K2gTYBYlXHDNhP0uR0kDlEj6NTyUWTwF+DZei47wTpPHGYOCr5+HyxkvJ0yrPNX2gn26dLRWQjZnuTkake7cAUdP8LMPrf4yO/LreJrfZp2tKpJNbjYN+fzcwp6jLXgiFmyGVDXE/lp7xtGG/ELGcEqsr++M78Zq7iI3cHJW639quEDBYbEcA8jmEFh3DSJDW7GHXnz01unPty8dVUXgio0l3mWU2V0/dZe5oYTa56xldYzOYjAWtZv36sO7yE9JseDJb0TcHhfIIITvNjcp7GiXpsy2MznGAFjr2xyvTdadE2pb7WInuH2i6o3MPN6EJRvdhelgsuAPcbkNYFvQD4GadYs6tOzCz3Pfnf6nUkM1MdjTv3awY7mgbE6glCapBIyS7A6Rg7dRbIv2g=
      on:
        tags: true
        branch: master
