language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
script: py.test --cov=. --cov-report term-missing
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
deploy:
  provider: pypi
  user: Avalara
  password:
    secure: Aewz/tatbjHVNs+xGveU1B3TrbHc/Ax+FcYOzCaRQgJRpE+p46HoECwoTpUdorMOUxwzT/wEenpcWH8fj1hAlbg9p26HpmBWvFTXa6nUmz4/okb0VLrDVOxTRBBBBgo2Ky16Se54og2uYKRgasf21n7pjH5OYojCgCktIZRoMeb+f7IWbQvu2in4eO+f3A43+eacNxyn6gdXoL0pF7yhYisHrgJsKkdMohYGW7xyg1yxfoo3vor7tMnDVgVDi8kBpXtX71wdAVDUj42T3PfpfEhEfpibpCDz36KaZ5vicy5sQqU6haBGjnnVLNPG6fBI6WLOQWnC4bT9iM/W7n8sFIe0PN0Se3ndCa6j7dzVe5rOKhpXLG+FrTXkSuI1C2acfQS02FK18qRRc00HKIIuTkWzdnD7rw9AF4zSP6YJUOPwd6bJrZhTkULKWd5nJVyZy73TCObfNBtEUHVOH6JylSmk2W+t6M4v0cL5YAlmpzCWShQ2LnNDMRSKtkTywpI7tOlWVbgdhkf6w6h5GLHNBXtpjFMiyDVdKJp3IgWp9VHYiyKvxnT4Z6pLEAGTHzQHfY0/FoKfUG03SC9MOdboTTMOtBPtMKRrPvx0Cnh4xDIOFjl1hzW8mAz2JsONt+GHzWYS0Jhkrbmjnw5hQ/IQ9UvxWxwrUamG7S9WlUA4sdg=
  on:
    tag: true
    branch: master
    python: 3.6
