language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
script: py.test --cov=. --cov-report term-missing
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
deploy:
  provider: pypi
  user: Avalara
  password:
    secure: rnfH9RYwdLwS1EKGLXvVr8pGYAHYHTgASrUKVqyiQdgimfbl7rnGkNJugE8TQtMVGiIemLy477+D/dMf87MvhDjq3pw9wgGIpJuF7TEfFuixD6TCq9I65G1PO+DLuOgOmzYR18eksv3Y9Z9ahr0PRnj0TFBHFdCt03/t8QAz4VCm5voeawobTy4qu9435VPge+I2RSDizDqR1yWattljVeacrVohGcZi/7mG4DYaivO0DG6bmwNZAVzM/Sw55dSbUSDBB3cfTi/iigj58+OP5IGw8j4ycOrnPmgCGkRW2mPG3lfnb3qKVWFXOHyqhODPFxngGsgYJEYWf+zGOjbP5xjn/6LAYxXsWfaQyT4b6O+Q7PMaA59oqWyGM0H2vHLd+BSHSVJsbCCAX3jAp1kC05x925gV1id8IK54+UnY2vPWcC3J1uJimXME7SSc0DKQWGxM+YcmxAC8PLM7+vv7glJXgJXerSE0Syztzp26fiqQsV7c1+0yBDfayHvHjAcMyO+wIKKa19mh5NrKcCXeW3LVxLn2gLZ/2/0H2aEdaeivGC/rGJS2TmcqKtrED7PbPghE2jiF5xTgHxsfXlqNR3smbQ68+g26fTkmVZKps7lEGbBsK2otvW3U+Wg9YZokMmr7+rg9KR3k622nkf4nk8IbuIqQmvUwXuxm5Q7tIJc=
  on:
    tag: true
    branch: master
    python: 3.6
