language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
script: py.test --cov=. --cov-report term-missing
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
deploy:
  provider: pypi
  user: Avalara
  password:
    secure: Kf+RzDNzbVlQCxy/MbJBgcKQPJfZi0RUoQUoJBLUQ7tEB7/K0yXywtEZhULt5bd8md9X0R+5ZT4bxSO5d2lUECasAC4mhz1FTOQD60mnXivjTX/YjFiR52y2RPjZ7PtMypW5PzBU0wgffI3OEByhtPhFILBEsMnWNGj5H7X08axfmFKKPx+lPwtcdvHSFpn1XoJwM3Yq7arKUGlJd9ThJBsa1x+f02GDiulX3KrfIQiPhTwPzLWmGYm1pIS6GSgysWvVYtP2HuVG/ErL8DYZdJ4RF94V/M/eGjqaT/Kv8SpRyVCXY2NBENw8B2W3VouSE5iCuWYsPO8ynZLRMOwDQSi9gIotLqFuvoaVJjeILFUytd2SnW/mspW2/49zuYSVSwzgACfB3D2bQ9/EUvxySenyjAW0gx1ozihOtvgBai5yI3yfPAFKdU/zHQhDiMAA57XzuFtUYSWFc06KvYjyJGmqtp8MZfbUJD/2MuWn8MlGxPHUvmzgWCvR34REBO6lQoRLwmIwRzb2J35AcFkuAh5EIj4HVd9UjkAWSd8eQdQQZSVd8eU6G41a7NwhgxniqFqcQG1HZlr27/B4YkBGZZ0EsxTLz80UO2FcJV+jnhjV8kb52mggn+86lJBbxZvrD+b8ZZCNqEwduOhLh22MRRMe1XjnsK+ytTWInoeOFRg=
  on:
    tag: true
    branch: master
    python: 3.6
