language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .[test]
- pip install -e .
- pip install pytest-cov
script: py.test --cov=. --cov-report term-missing
env:
  global:
  - CI=true
  matrix:
  - TEST_DOC=true
notifications:
  email: false
  slack:
    rooms:
    - secure: R8rDp7cXw0h40KKgUSg/VlZsf8y5FkqzcR06HpgN/OCOmtp1tum+zsmO3kb1yjlmYcxsW3AqtZBvOVmKsTeHfAJgt9uKvoW770kGXRPnCpqpJ6eCs47sOTNrwyUJIOwyFbZKFicgeFygIjnU5sL7NWMC8ZE/bGWMXjpbzx4jXYgwQrSbY5kIoH+aZXg4UyVczX6vv/7ItE4VhxPMMI+eRC/sqK3A/fbRvDnwyWnwRfNnQhfG5bCMFgF1TEKsHBt3SZjPTqr1WGn8B8loVLOw1LVpmBWBNOy0hUiSGq5ZZ8ZNOvJa3Nuno3+6TfmB0r/jmg2CgARdLkGhjtVbhsRIpT4SbEppo66LEUFhhuWmi9Y0G2sbV2HjKFUw0cCX7zezH/d8h2BeNyfSZ0gYKC1OWnnlY8d+mcVZLmd3V46YUM/rplVZMlE0jxPrF6aS6ePtDh694tgLEHBgSExDzqNMeACYjM674X6rKoOcX34pHu3MegnA8s7TUB1d4RexS2IsHB4cPurR4wcdAKIAqpFO3u07Ab0TxV0YuJuiwS2r3cckFsf107T7uT8TPRxfUv57Qncdd2XomS6+VsE6TIfyfgDnkoIoADUG+625V1EXiYnsUUCTrcdkr2HkGXBRxqY8B7t76tEe6IryoG4yl6uiOG3afqaOJjKedHEvf4K2+Sc=
    on_success: never
    on_failure: never
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}%{result}
deploy:
  provider: pypi
  user: Avalara
  password:
    secure: di7X9tU5//ZBO475+Sh1qtH/Tb5+bPzQKJiW5vnGRr+/6Pv5WRp3waT4u0ibr8dD5rOVuYrNEYANtHlHqEGS8ytayfk5MXLipFEMeOuHZw+uUZ9ZSV2deJOsivkVISqVdBORlhfgAnINjBAgX2skIgxpP4ffiBm35fVciVbmUxoBIDS/NVom2c8tBCjNt4VhUdLn9ZtvoOXhmbLE5K3KHGVDIzibMWrZS0YxluuN38QaNs+mmiikCNsOVO/cebMi21f9S4v+VWZ+Aqi+k/HA52Gb7NJDLz2Ai7tTwuiVF+H/EjkAZlEM/pkhvP/GZIb6bCqZYx9qNbg9zDe+gpGK87sioxjTRv/IJTqw4T9g2kzhm5Mmpgz61WYacTBXj4q2Yt/M0i6L08oqsAw4RVn8D7e6KfmpAW4t2CsiQshPKS+CkB6uoluuzu2czdKBWVgtmhjCswe5JBOh2F1na432Iz/zIovXo7dkketc6/t6qTcv5MvcNEDSFkzmEpgmLieizyVNvr0S6yNVnoQ5AwWMb0mOJPZlqrSaJ6Y+tE/dFux3mqREqKLR28aOpw8eAZ5JFeUFAsxtuZNYb7dJ+6zyQY3oqkw1U4L4LmbiMoiwkZKUWdiLFvZ9Pxss6GVVSJX4G0B7YNjiOjyrnAlOwL9Cu6xl6x86K+XlgW44qrZKD58=
  on:
    tag: true
    branch: master
    python: 3.6
